@baseUrl = http://localhost:3000
@apiUrl = {{baseUrl}}/api/v1
@auth_token=""

GET {{apiUrl}}/auth

# sign up with email
POST {{apiUrl}}/auth/sign-up/email
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "StrongPass123"
}

###

# sign in
POST {{apiUrl}}/auth/sign-in/email
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "StrongPass123"
}

###

# get session (after login, cookie or token based)
GET {{apiUrl}}/auth/session
Authorization: Bearer {{auth_token}}

###

# logout
POST {{apiUrl}}/auth/sign-out
Authorization: Bearer {{auth_token}}
